apiVersion: apps/v1
kind: Deployment
metadata:
  name: local-demo-deployment
spec:
  replicas: 3
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: local-demo
  template:
    metadata:
      labels:
        app: local-demo
    spec:
      containers:
      - image: davidle1969/demo-harness:8
        name: local-demo-container
        ports:
        - containerPort: 80
